# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e3c8338f15d2b2c7c3ab1fc7a8be38acb8c5012c0e32270d41447d1b8fb7a882aad42f528d2dd48956be55cbc57d87e6a640b45fe455d26d31c89de491778ee

test:
  secret_key_base: eb474d95da6cfa9e349ee22decae9081b98d9d95997a4486930637f49e0f90ac0f17338fb909fb535e5689ed6770e5a5f1d6d58d2ea1c69f76e908ddd59cefc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
